server:
  port: 8080


spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: mybaits_plus
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://106.13.188.27:3306/yyc?useSSL=false
#    username: root
#    password: root
  shardingsphere:
    datasource:
      names: seata
      seata:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.220:3306/seata?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: ly
        password: 123456
    sharding:
      tables:
        t_user:
          actual-data-nodes: seata.t_user_$->{0..2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: t_user_$->{id % 3}
          key-generator:
            column: id
            type: SNOWFLAKE
    props:
      sql:
        show: true