server:
  port: 8080
  servlet:
    context-path: /dubbo


#dubbo:
#  application:
#    name: annotation-provider
#  registry:
#    address: zookeeper:124.70.135.171:2181
#  protocol:
#    name: dubbo
#    port: 20880
