server:
  port: 8081
  servlet:
    context-path: /aq

spring:
  activemq:
    broker-url: tcp://148.70.168.104:61616
    user: admin
    password: admin
    pool:
      enabled: false
      max-connections: 50